repo_url: https://txyyh.github.io/fdroid-repo/repo
repo_name: FlClash
repo_description: >-
  The official F-Droid repository for FlClash.

repo_keyalias: KEYALIAS
keystore: keystore.keystore
keystorepass: KEYSTOREPASS
keypass: KEYPASS
keydname: KEYDNAME